// MODELS

// - Note
const NOTE_MIN_CONTENT_LENGTH = 5;
const NOTE_MAX_CONTENT_LENGTH = 1000;

// - Comment
const COMMENT_MIN_CONTENT_LENGTH = 2;
const COMMENT_MAX_CONTENT_LENGTH = 200;

module.exports = {
  NOTE_MIN_CONTENT_LENGTH,
  NOTE_MAX_CONTENT_LENGTH,

  COMMENT_MIN_CONTENT_LENGTH,
  COMMENT_MAX_CONTENT_LENGTH,
};
