name: Testing pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  client-test:
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: ./client
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm install
      - run: npm run lint
      - run: npm run test

  server-test:
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: ./server
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Create .env with Github Secrets
        run: |
          touch .env
          echo POSTGRES_URL_TEST=${{ secrets.POSTGRES_URL_TEST }} >> .env
      - run: npm install
      - run: npm run lint
      - run: npm run test