name: Server tests with pg in a container

on:
  push:
    branches:
      - containers

jobs:
  server-container-test:
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: ./server

    # Service containers to run with `server-container-test`
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_PASSWORD: postgres
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps tcp port 5432 on service container to the host
          - 5432:5432

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm install
      - run: npm run lint

      - run: npm run test
        env:
          POSTGRES_URL_TEST: 'postgres://postgres:postgres@localhost:5432/postgres';